# Generated by Django 5.1.7 on 2026-01-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_user_alter_cart_cart_id_alter_cart_data_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
