# Generated by Django 5.1.7 on 2026-01-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_rename_data_added_cart_date_added_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
